# Generated by Django 3.1.4 on 2021-01-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='acronym',
        ),
        migrations.AddField(
            model_name='translation',
            name='acronym_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Translationacronym_en'),
        ),
        migrations.AddField(
            model_name='translation',
            name='acronym_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Translationacronym_fr'),
        ),
    ]
