# Generated by Django 3.1.4 on 2021-01-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_auto_20210128_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servedetats',
            name='drug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
