# Generated by Django 3.1.4 on 2021-01-29 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_servedetats_type_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servedetats',
            name='type_data',
        ),
        migrations.AddField(
            model_name='servedetats',
            name='amount',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servedetats',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DrugServedEtat', to='med.drug'),
        ),
    ]
