# Generated by Django 3.1.4 on 2021-01-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0005_auto_20210129_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='variousparameters',
            name='big_total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
