# Generated by Django 3.1.4 on 2021-01-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0007_auto_20210130_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
