# Generated by Django 3.1.4 on 2021-02-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0008_drug_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='variousparameters',
            name='cameg_total_amount_served',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variousparameters',
            name='cameg_total_amount_served_now',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variousparameters',
            name='ih_total_amount_served',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variousparameters',
            name='ih_total_amount_served_now',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
