# Generated by Django 3.1.4 on 2021-02-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0010_auto_20210202_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etats',
            old_name='single_mount',
            new_name='single_amount',
        ),
        migrations.RenameField(
            model_name='etats',
            old_name='total_mount',
            new_name='total_amount',
        ),
    ]
