# Generated by Django 3.1.4 on 2021-01-28 11:05

import auths.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='images/DefaultUserIcon.png', null=True, upload_to=auths.models.user_path)),
                ('profile_pic_thumb', models.ImageField(blank=True, default='images/DefaultUserIcon.png', null=True, upload_to=auths.models.user_path_thumb)),
                ('biography', models.TextField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=30, null=True)),
                ('is_creator', models.BooleanField(default=False, help_text="Designates that this user is in creator's team")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
